import { useCallback, useEffect, useState } from 'react'
import { Activity, RefreshCw, Save, Settings2, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { DraftNumberInput } from '@/components/ui/draft-number-input'
import { Switch } from '@/components/ui/switch'
import { SegmentedPillGroup } from '@/components/ui/segmented-pill-group'
import { useTranslation } from 'react-i18next'
import TwoFAImport from '../components/TwoFAImport'
import { credentialRequest, type CredentialAccount, type CredentialOverview } from '@/lib/credentialOps'

export default function CredentialOps() {
  const { t } = useTranslation()
  const [data, setData] = useState<CredentialOverview | null>(null)
  const [selected, setSelected] = useState<CredentialAccount | null>(null)
  const [view, setView] = useState<'accounts' | 'import' | 'jobs'>('accounts')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { try { setData(await credentialRequest<CredentialOverview>('/credential-ops')); setError('') } catch (err) { setError(String(err)) } }, [])
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 5000); return () => clearInterval(timer) }, [load])
  async function action(path: string, method = 'POST', body?: unknown) { setBusy(true); try { await credentialRequest(path, method, body); await load() } catch (err) { setError(err instanceof Error ? err.message : t('credentialOps.failed')) } finally { setBusy(false) } }
  return <main className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6">
    <header className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-xl font-semibold">{t('credentialOps.title')}</h1><Button variant="outline" size="icon" title={t('credentialOps.refresh')} onClick={() => void load()}><RefreshCw className="size-4" /></Button></header>
    <SegmentedPillGroup value={view} onChange={setView} label={t('credentialOps.views')} className="max-w-xl" options={[{ value: 'accounts', label: t('credentialOps.accountsView') }, { value: 'import', label: t('credentialOps.firstLogin') }, { value: 'jobs', label: t('credentialOps.jobsView') }]} />
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
    {data && !data.enabled && <p className="text-sm text-muted-foreground">{t('credentialOps.disabled')}</p>}
    {!data && !error && <p className="text-sm text-muted-foreground">{t('credentialOps.loading')}</p>}
    {view === 'import' && data?.enabled && <div className="max-w-3xl"><TwoFAImport onSaved={() => void load()} sessionStudioConfigured={data.session_studio_configured} /></div>}
    {view === 'accounts' && <>
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-muted-foreground"><tr>{['account', 'probeResult', 'failStreak', 'nextProbe', 'autoLogin', 'actions'].map(key => t(`credentialOps.${key}`)).map(label => <th key={label} className="whitespace-nowrap px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{data?.accounts.map(account => <tr key={account.account_id} className="border-b"><td className="max-w-64 px-3 py-3"><div className="truncate">{account.name}</div><span className="text-xs text-muted-foreground">#{account.account_id}</span></td><td className="px-3 py-3"><span title={account.probe_detail}>{t(`credentialOps.probe.${account.probe_state}`, { defaultValue: account.probe_state })}</span></td><td className="px-3 py-3">{account.fail_streak}</td><td className="whitespace-nowrap px-3 py-3">{account.enabled ? new Date(account.next_probe_at).toLocaleString() : t('credentialOps.off')}</td><td className="px-3 py-3">{account.auto_relogin ? t('credentialOps.on') : t('credentialOps.off')}</td><td className="px-3 py-3"><div className="flex gap-1"><Button size="icon" variant="ghost" title={t('credentialOps.configure')} onClick={() => setSelected({ ...account })}><Settings2 className="size-4" /></Button><Button size="icon" variant="ghost" title={t('credentialOps.probeNow')} disabled={busy || !data?.enabled} onClick={() => void action(`/accounts/${account.account_id}/credential-ops/probe`)}><Activity className="size-4" /></Button></div></td></tr>)}</tbody></table>{data?.accounts.length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">{t('credentialOps.noAccounts')}</p>}</div>
      {selected && <section className="space-y-5 border-t pt-5"><div className="flex items-center justify-between"><h2 className="text-base font-semibold">{selected.name}</h2><Button size="icon" variant="ghost" title={t('credentialOps.closeConfig')} onClick={() => setSelected(null)}><X className="size-4" /></Button></div><div className="flex flex-wrap gap-5 text-sm"><label className="flex items-center gap-2"><Switch checked={selected.enabled} onCheckedChange={value => setSelected({ ...selected, enabled: value })} />{t('credentialOps.enableMonitor')}</label><label className="flex items-center gap-2"><Switch checked={selected.auto_relogin} onCheckedChange={value => setSelected({ ...selected, auto_relogin: value })} />{t('credentialOps.autoRelogin')}</label></div><div className="grid max-w-3xl gap-4 sm:grid-cols-3">{([['interval_seconds', 'probeInterval', 60, 86400], ['failure_threshold', 'failureThreshold', 1, 20], ['cooldown_seconds', 'cooldown', 60, 86400]] as const).map(([key, label, min, max]) => <label key={key} className="space-y-1 text-sm">{t(`credentialOps.${label}`)}<DraftNumberInput min={min} max={max} value={selected[key]} onValueChange={value => setSelected({ ...selected, [key]: value })} /></label>)}</div><Button variant="outline" disabled={busy || !data?.enabled} onClick={() => void action(`/accounts/${selected.account_id}/credential-ops/monitor`, 'PUT', selected)}><Save className="size-4" />{t('credentialOps.saveRules')}</Button>{data?.enabled && <div className="max-w-3xl border-t pt-5"><TwoFAImport accountId={selected.account_id} onSaved={() => void load()} sessionStudioConfigured={data.session_studio_configured} /></div>}</section>}
    </>}
    {view === 'jobs' && <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-muted-foreground"><tr>{['job', 'account', 'statusStage', 'attempts', 'created', 'actions'].map(key => t(`credentialOps.${key}`)).map(label => <th key={label} className="whitespace-nowrap px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{data?.tasks.map(task => <tr key={task.ID} className="border-b"><td className="px-3 py-3">#{task.ID}</td><td className="px-3 py-3">{task.AccountID || t('credentialOps.firstImport')}</td><td className="px-3 py-3"><p>{t(`credentialOps.status.${task.Status}`, { defaultValue: task.Status })} / {t(`credentialOps.stage.${task.Stage}`, { defaultValue: task.Stage })}</p>{task.Error && <p className="text-xs text-destructive">{task.Error}</p>}</td><td className="px-3 py-3">{task.Attempt}</td><td className="whitespace-nowrap px-3 py-3">{new Date(task.CreatedAt).toLocaleString()}</td><td className="px-3 py-3">{['queued', 'running'].includes(task.Status) && <Button size="icon" variant="ghost" title={t('credentialOps.cancelJob')} disabled={busy} onClick={() => void action(`/credential-ops/login/${task.ID}`, 'DELETE')}><X className="size-4" /></Button>}</td></tr>)}</tbody></table>{data?.tasks.length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">{t('credentialOps.noJobs')}</p>}</div>}
  </main>
}
